repository: chrisramiro/chrisramiro.github.io.

# Site Variables
title: Christian Ramiro
email: chrisram@berkeley.edu
email2: chris05ram@gmail.com
baseurl: ""
url: "https://chrisramiro.github.io"

facebook: "https://www.facebook.com/Chris05Ram"
instagram: "https://www.instagram.com/chris05ram"
spotify: "https://play.spotify.com/user/chris05ram"
github: "https://www.github.com/chrisramiro"
linkedin: "https://www.linkedin.com/in/chrisramiro"

#Design Variables
blue_l: 
blue_d: #155065
greyblue: #2a343e
orange_l: #ffba33
orange_d:

#Default Values
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
